### PR TITLE
Arduino Unit Tests

### LINKED ISSUE #68: Arduino Unit Testing
### User Story
As a developer, I want to create unit testing to ensure that every individual component of the arduino code is working as intended.

### Acceptance Criteria

- Unit testing should be available for the developers to check the components.

### PR DESCRIPTION
**Pull request by Marble879**
### Changes

1. Add unit tests for the business logic of the Arduino code/sketch.
2. Refactor the Arduino sketch to become testable.
     - Sketch now makes use of wrappers.
     - Sketch now uses a controller file, which contains the business logic.

 

### Issues

Resolves #68

### CODE REVIEW

**Review by puerto-hub — APPROVED** [review]
The unit tests look great. The refactored code looks good too.

**Review by MarkusJ299 — APPROVED** [review]
Looks good overall and good that we now have unit testing. I think it could've been good to make a separate branch for refactoring since there are so many changes in this PR. However, I understand if it was done on the go to enable unit testing so it also makes sense. Nice work!

**Review by JihanP — APPROVED** [review]
The unit testing looks very well implemented! Really good job!

**Review by NilsDunlop — APPROVED** [review]
I tested the unit tests and they seem to work really well! Well done on making a lot of arduino parts testable. We will take over the world with our unit tests! 🚀

**Pull request merged**
