### PR TITLE
Finalize Readme

### LINKED ISSUE #60: Documentation update
### User Story
As a medical worker, I want to have updated documentation so that I would be able to use the app properly.

### Acceptance Criteria
- Documentation should at least 2 paragraphs of explanation.

### PR DESCRIPTION
**Pull request by NilsDunlop**
### Changes

1. Add gifs to visualize actions in wiki pages and readme.
2. Add images for the wiki pages and readme.
3. Add all remaining nessesary documentation in the readme.
4. Add project demo video.

### Issues

Resolves #60

### CODE REVIEW

**Review by Kevinayad — APPROVED** [review]
Good Job!

**Review by JihanP — CHANGES_REQUESTED** [review]
For the final video maybe we should have a small text or something telling the reader that the picture is clickable?

**Comment by NilsDunlop** [comment]
> For the final video maybe we should have a small text or something telling the reader that the picture is clickable?

I tried to add that in the last commit by that when hovering over the image the Youtube title is hinted to the user. I feel adding a header of some sort would make it less appealing.

**Review by Marble879 — APPROVED** [review]
Readme looks great 👍

**Review by MarkusJ299 — APPROVED** [review]
Like Jihan said there could maybe be something to show that it is a video. Otherwise I think we are good to go. Good job everyone!

**Review by JihanP — APPROVED** [review]
The ReadMe looks amazing! I could agree that a header would not look appealing

**Review by gusasino — COMMENTED** [review]
Everything looks great!!!

**Pull request merged**
