### PR TITLE
Fix bug where connection between app and car is not terminated when exiting the joystick menu.

### LINKED ISSUE #40: [BUG] Connection between car and app is not closed once joystick screen is exited.
### Description
When going back to the main menu from the joystick screen, the app is not disconnected from the car. This may cause problems when trying to select different cars in the future.

### PR DESCRIPTION
**Pull request by Marble879**
### Changes

- Fixes the bug where the connection is not terminated when exiting the joystick menu.
- Refactored code. 

### Issues:
Resolves #40

### CODE REVIEW

**Review by NilsDunlop — APPROVED** [review]
Nicely done changing the main functions into methods. It makes a lot more sense now and solves the bug we had difficulties with!

**Review by JihanP — APPROVED** [review]
Great that you refactored the code so that it looks more readable and good job on fixing the bug! The code runs smooth👍🏻

**Review by Kevinayad — APPROVED** [review]
Nice fix!

**Review by MarkusJ299 — APPROVED** [review]
Looks good!

**Pull request merged**
