### PR TITLE
Fix joystick publish spam bug

### LINKED ISSUE #25: [BUG] MQTT broker spammed with joystick instructions when joystick is not being moved.
When the joystick is not being used, there is a constant publishing of unnecessary joystick instructions.

### PR DESCRIPTION
**Pull request by Marble879**
### Changes:

- Fixes the issue where there would be spam publishes from joystick instructions

### Issues:

- Resolves #25

### CODE REVIEW

**Review by JihanP — APPROVED** [review]
Everything looks good, nice fix! Do not see anything wrong

**Review by NilsDunlop — APPROVED** [review]
This solves the joystick issue. Great work!

**Review by MarkusJ299 — APPROVED** [review]
Good job. To me the code looks good.

**Review by Kevinayad — APPROVED** [review]
looks good!

**Review by puerto-hub — APPROVED** [review]
Nicely done, very good fix.

**Comment by gusasino** [comment]
everything looks great!

**Review by gusasino — COMMENTED** [review]
everything looks good!

**Pull request merged**
