### PR TITLE
Android Unit Tests

### LINKED ISSUE #55: Android Unit Testing
### User Story
As a developer, I want to create unit testing to ensure that every individual component of the android app is working as intended.

### Acceptance Criteria

- Unit testing should be available for the developers to check the components.

### PR DESCRIPTION
**Pull request by NilsDunlop**
### Changes

1. Add instrumented android unit tests for each of the screens.
2. Add custom android matchers to be able to tests app instruments such as the recycler view, images, and toast messages.
3. Slightly refine code to fine-tune the final product.

### Issues
Resolves #55

### CODE REVIEW

**Review by Marble879 — APPROVED** [review]
Great work on the unit tests, they look and run well! Also, great job on  refactoring  :+1: it improves readability and describes the purpose of the adapter file better!

**Review by Kevinayad — APPROVED** [review]
Good job!

**Review by MarkusJ299 — APPROVED** [review]
The unit testing and refactoring looks good. Just a small note for the future: Since there are many files changed here, I think it would've been a good idea to do unit testing on one branch and refactoring on a separate branch to keep things tidy. Good job nonetheless!

**Review by puerto-hub — APPROVED** [review]
Great job on the unit tests and refining code!

**Review by JihanP — APPROVED** [review]
Wow I'm impressed with the unit test, it looks really good and well implemented!

**Review by gusasino — COMMENTED** [review]
everything looks good!

**Pull request merged**
