### PR TITLE
Update UI and create sprint 3 progress video

### LINKED ISSUE #74: Update Server Selection
Update the server selection screen by adding a medcar driving animated gif.  This removes the unused space in the bottom and keeps the users attention.

### LINKED ISSUE #75: [DOCUMENTATION] Update readme with sprint 3 progress video
### Description 
Add sprint  3 progress video to readme file in order to increase the traceability of the projects progress throughout each sprint. 

This may give the user a better understanding of how the app came about and the progress along the way.

### PR DESCRIPTION
**Pull request by NilsDunlop**
### Changes

1. Update server selection screen by adding a medcar gif to the bottom of the screen.
2. Add sprint 3 progress video to readme file.

### Issues
Resolves #74
Resolves #75

### CODE REVIEW

**Review by Marble879 — APPROVED** [review]
Great work :+1: The GIF in the server selection screen looks great!

**Review by puerto-hub — APPROVED** [review]
The gif on the bottom of the server selection screen looks really good! And the sprint 3 video seems to cover everything changed from the previous sprint.

**Review by JihanP — APPROVED** [review]
The gif looks really good in the server selection screen! And the video is well made! Nice job!

**Review by MarkusJ299 — APPROVED** [review]
Good job with the gif and video!

**Pull request merged**
