### PR TITLE
Auto button bug fix

### LINKED ISSUE #64: [BUG] Autonomous driving button is not available when in landscape mode
### Description
When testing, the autonomous driving button is no longer available when switching to landscape mode while on the manual control screen.

### LINKED ISSUE #65: [BUG] Switching from landscape to portrait mode, and then pressing the back button, causes the app to crash
### Description
When testing, switching between landscape mode and portrait mode  (while in the manual control screen) causes a crash  when then pressing the back button.

### Sequence of actions to reach this bug
(when in manual control screen)
1. Switch from portrait to landscape mode
2. Switch back from landscape to portrait mode
3. Press back button

### LINKED ISSUE #66: [BUG] When in landscape mode, pressing back (from the manual control screen) crashes the app
### Description
When having landscape model enabled while in the manual control screen, the app crashes after pressing the back button.

### Sequence of actions to reach this bug
(while in the manual control screen)
1. Switch to landscape mode
2. Select the back button

### PR DESCRIPTION
**Pull request by NilsDunlop**
### Changes

1. Fixed landscape mode bugs by adding the auto button to the manual control landscape view.
2. Simplied onBackPressed method in MainActivity.

### Issues

Resolves #64
Resolves #65
Resolves #66

### CODE REVIEW

**Review by JihanP — APPROVED** [review]
Looks nice, good fix!👏🏻

**Review by puerto-hub — APPROVED** [review]
Good bug fix, now you can return from the manual control screen.

**Review by Marble879 — APPROVED** [review]
Everything looks great code wise and when testing! Great job on fixing the bugs :+1:

**Review by MarkusJ299 — APPROVED** [review]
The code looks good to me and nice simplification of onBackPressed().

**Review by Kevinayad — APPROVED** [review]
Good bug fixes!

**Pull request merged**
