### PR TITLE
Fix bug where car makes a sharp right when stopping.

### LINKED ISSUE #36: [BUG] When stopping, the car makes a sharp turn.
### Description

The car makes a sharp turn to the right when stopping. This is due to an angle of 90 being published to the MQTT broker from the android app when letting go of the joystick.

### PR DESCRIPTION
**Pull request by Marble879**
### Changes

- Fixed the issue where the car would turn hard right when stopping.

### Issues:

- Resolves #36

### CODE REVIEW

**Review by NilsDunlop — APPROVED** [review]
Good bug fix and the code looks a lot more readable now. Great work!

**Review by MarkusJ299 — APPROVED** [review]
Seems to work fine.

**Review by JihanP — APPROVED** [review]
Tested the code and it works really good! Good job!

**Review by puerto-hub — APPROVED** [review]
Good idea to turn the feature into a method. Great!

**Review by Kevinayad — APPROVED** [review]
nice fix!

**Review by gusasino — COMMENTED** [review]
everything looks great!

**Pull request merged**
