### PR TITLE
Camera stream

### LINKED ISSUE #29: Live camera when driving the car
**User Story**

- As a medical worker I want a camera view to be able to see where the car is while manually maneuring so that I can deliver medicine or food to my patients.

**Acceptance Criteria**

- The medical worker should be able to see the camera car view while driving.

### PR DESCRIPTION
**Pull request by Marble879**
### Changes

Implement camera streaming between Arduino car and Android app

### Issues
Resolves #29

### CODE REVIEW

**Review by NilsDunlop — APPROVED** [review]
I don't see anything that needs to be changed. The code is refactored and very readable. Well done guys! 🥇

**Review by JihanP — APPROVED** [review]
The code looks really good, there's no issue or problem that caught my attention. Nice job on encapsulating some of the variables that were not encapsulated before!

**Review by Kevinayad — APPROVED** [review]
Well needed feature improvement, good job!

**Review by gusasino — COMMENTED** [review]
good work guys!

**Pull request merged**
