### PR TITLE
Car selection check to enable button 

### LINKED ISSUE #47: Enable connect button after RecyclerView item click
### User Story
As a medical worker, I want the system to only allow medical workers to connect to a car if a specific car has been selected.

### Acceptance Criteria
- The main screen connect button upon starting upp the app should be disabled until a car has been selected to which it then should connect to the respective car manual control screen.
- The user should receive feedback on what to do next if pressed on a disabled button.

### PR DESCRIPTION
**Pull request by NilsDunlop**
### Changes

1. Add car selection check in order to connect to the manual maneuvering.
2. Display feedback to the user upon pressing on a disabled button.
3. Add missing code related to the credits pop up.

### Issues
Resolves #47

### CODE REVIEW

**Review by JihanP — APPROVED** [review]
I tested the code and there dosen't seem to be any bugs and the code looks readable for me.

**Review by Marble879 — APPROVED** [review]
Great job, the code looks good :+1:  When testing, I really liked how the button was grayed out when it was disabled.

**Review by puerto-hub — APPROVED** [review]
Looks really well made. Good job!

**Review by MarkusJ299 — APPROVED** [review]
Makes sense to have the button grayed out unless a car is selected. The code seems fine. Good job!

**Review by gusasino — COMMENTED** [review]
Everything looks good!

**Review by Kevinayad — APPROVED** [review]
Looks good! Great job

**Pull request merged**
