### PR TITLE
MQTT Connectivity 

### LINKED ISSUE #13: CI connectivity
**User Story**

- As a developer, I want continuous integration to be a part of the arduino MQTT connection, so that I know the new code I am introducing will not break the system.

**Acceptance Criteria**
- The CI should be done on github actions using yml files and tests upon push requests.
- CI should return the result of whether or not the newly introduced code works.

### LINKED ISSUE #14: MQTT connectivity
### User Story

- As a medical worker, I want the app to be able to connect to the car using the internet, so I can start using it.
### Acceptance Criteria

- The MQTT protocol is able to connect to the app and SMCE.

### PR DESCRIPTION
**Pull request by JihanP**
Resolves #14 
Resolves #13

### CODE REVIEW

**Review by puerto-hub — APPROVED** [review]
Connectivity looks good

**Review by Marble879 — APPROVED** [review]
Looks good to me! :+1:

**Review by NilsDunlop — APPROVED** [review]
Great work on the connectivity! Looks good👍

**Review by MarkusJ299 — APPROVED** [review]
This looks good.

**Comment by platisd** [comment]
Did the **entire** team work on this?! Or rather, did the entire team work on **each and every** commit?

**Comment by Marble879** [comment]
> Did the **entire** team work on this?! Or rather, did the entire team work on **each and every** commit?

Hey,  we originally split into 2 groups, one for the MQTT connectivity and the other for the manual maneuvering. There were some bugs with the connectivity, so we decided that the manual maneuvering group would help out in resolving these. We now plan to tackle the rest of the issues/user stories in the originally planned groups

**Pull request merged**
