### PR TITLE
#60 Update security description

### PR DESCRIPTION
**Pull request by Kevinayad**

### CODE REVIEW

**Review by gusasino — COMMENTED** [review]
looks good 👍

**Comment by Marble879** [comment]
It would be better to add this to the FinalizeReadme branch, and also including a #60 in the commit message for better traceability.

**Comment by Kevinayad** [comment]
> It would be better to add this to the FinalizeReadme branch, and also including a #60 in the commit message for better traceability.

Will do!

**Review by puerto-hub — APPROVED** [review]
Looks good! Maybe next time you could commit to the FinalizeReadme directly to make it easier.

**Review by Marble879 — APPROVED** [review]
The security description looks great!

**Review by NilsDunlop — APPROVED** [review]
Nice update to the security description!

**Review by MarkusJ299 — APPROVED** [review]
That looks good to me!

**Review by JihanP — APPROVED** [review]
Good work!

**Pull request merged**
