### PR TITLE
Manual maneuvering

### LINKED ISSUE #17: Handle the speed with a Joystick
### **User story:**
- As a medical worker, I want to be able to adjust the speed of the car depending on how far forward I hold the joy stick, so that I can control how fast the car moves

### **Acceptance criteria:**
- Moving the joystick further out will increase the speed of the car.

### LINKED ISSUE #19: The car should move in all directions determined by the joystick
### User Story
- As a medical worker, I want the car to move in all directions, so that I can control where the car moves

### Acceptance Criteria
- The car should understand angles and directions based on the joystick 
- The car should move based on the position of the joystick.

### PR DESCRIPTION
**Pull request by Marble879**
Implements manual maneuvering so that the user can use a joystick to manually control the car

Resolves #19 
Resolves #17

### CODE REVIEW

**Comment by JihanP** [comment]
Everything looks good! Good job guys!

**Comment by gusasino** [comment]
Looks good!

**Review by JihanP — APPROVED** [review]
Looks good!

**Review by Kevinayad — APPROVED** [review]
Looks good!

**Review by gusasino — APPROVED** [review]
looks good!

**Pull request merged**
