### PR TITLE
Refactor output text/strings code

### LINKED ISSUE #52: [REFACTOR] Refactor strings that will be displayed in the UI.
### Description
Based on the TA's suggestion, it may be good to refactor the strings that would be displayed in the UI by moving them to the strings.xml file.

This may improve maintainability of messages/strings that will be displayed on the app to the user.

### PR DESCRIPTION
**Pull request by Marble879**
### Changes

1. Move all strings that would be output to the UI to the strings xml file for better maintainability of output messages/button text.
2. Add labels to the strings xml file for improved readability/organization.

### Issues

Resolves #52

### CODE REVIEW

**Review by MarkusJ299 — APPROVED** [review]
Everything looks good to me. This should make the code much easier to maintain if we need to modify any of the strings.

**Review by JihanP — APPROVED** [review]
Nice improvments to our code! I think it looks good, did not find anything that should be changed

**Review by puerto-hub — APPROVED** [review]
Really interesting change. Good job!

**Review by NilsDunlop — APPROVED** [review]
Now all of our strings are stored in one place and the code more readable, great work!

**Pull request merged**
