### PR TITLE
Adds obstacle avoidance to manual control

### LINKED ISSUE #15: The car stops moving while it is being manually controlled when an obstacle is detected
### User Story

- As a medical worker, I want the car to stop driving when an obstacle is detected, so that it doesn’t get damaged while manually controlling it.

### Acceptance Criteria

- The car should stop driving when an obstacle is detected about 30cm away from it, even if the user keeps accelerating.
- The car should stop 100% of the time when an obstacle is detected 30cm away from it.

### PR DESCRIPTION
**Pull request by Marble879**
### Changes:

- Implements car stopping when an obstacle is detected about 30 cm away.
- Makes stopping the car with joystick smoother.

### Issues:

- Resolves #15

### CODE REVIEW

**Review by JihanP — APPROVED** [review]
I do not see any errors with the code, It seems fine for me. Nice work!

**Comment by gusasino** [comment]
Nice work!

**Review by gusasino — COMMENTED** [review]
nice work!

**Review by Kevinayad — APPROVED** [review]
seems good keep it going!

**Pull request merged**
