### PR TITLE
Status text when connected to server

### LINKED ISSUE #18: Notifications on the connectivity with the car.
### User Story

- As a medical worker I want to have notifications on the connectivity with the car, so that I know if I am connected to the car or not.

### Acceptance criteria

- The User should be notified on the app once the connection to the app has been lost/gained.
- There should be an indicator that will be green when connected, and red when not connected.

### PR DESCRIPTION
**Pull request by JihanP**
Resolves #18

### CODE REVIEW

**Review by NilsDunlop — APPROVED** [review]
Great additional feature, well done!

**Review by Marble879 — APPROVED** [review]
Everything looks great! Good job :+1:

**Review by puerto-hub — APPROVED** [review]
Really good status texts.

**Review by MarkusJ299 — APPROVED** [review]
Everything seems fine

**Pull request merged**
