### PR TITLE
Move credits popup to server selection screen

### LINKED ISSUE #57: Move credits popup to server selection screen
Move the credits popup from car selection screen to server selection screen, so that it is displayed on the first screen of the app.

### PR DESCRIPTION
**Pull request by JihanP**
### Changes

1. Change the location of the credits popup so that it is shown in the Server selection screen instead of the main activity screen

### Issues
Resolves #57

### CODE REVIEW

**Review by Marble879 — APPROVED** [review]
The credit pop up looks great for both, landscape and portrait mode! Great job :+1:

**Review by puerto-hub — APPROVED** [review]
Nice job moving the credits!

**Review by NilsDunlop — APPROVED** [review]
Nice change and well done guys! Maybe the credit button would look better inline with the logo but we can look into that more when we perfect each app screen 👍

**Review by gusasino — COMMENTED** [review]
everything looks good!

**Pull request merged**
