### PR TITLE
Obstacle notification

### LINKED ISSUE #16: Notifications for obstacles
### User Story
As a medical worker, I want to be notified when an obstacle is detected, so that I can stay up to date with what is happening to the car at a given moment.

### Acceptance Criteria

- The app should notify the user about obstacles that the car is encountering.

- The users phone should vibrate when an obstance is in front of the car.

### PR DESCRIPTION
**Pull request by Marble879**
### Changes

1. Add a notification pop up when an obstacle is detected in the front/behind the car.
2. Add a vibration where an obstacle is detected in front/behind the car.
3. Add a vibration log to logcat so that we can confirm when/if vibrations are actually taking place.

### Issues
Resolves #16

### CODE REVIEW

**Review by Kevinayad — APPROVED** [review]
Good job😃

**Review by puerto-hub — APPROVED** [review]
Looks really well made!

**Review by MarkusJ299 — APPROVED** [review]
I think this looks good. Nice work!

**Review by gusasino — COMMENTED** [review]
everything looks great!

**Review by NilsDunlop — APPROVED** [review]
I really like the addition of the phone vibration! Really well written code. Well done 👑

**Review by JihanP — APPROVED** [review]
Great job! Looks very good

**Pull request merged**
