### PR TITLE
Removal of unused imports

### LINKED ISSUE #77: [FIX] Unused imports in Manual Control and Main Activity
### Description
There are some unused imports in the Manual Control and Main Activity class that should be removed

### PR DESCRIPTION
**Pull request by MarkusJ299**
### Changes

1. Removes unused imports in ManualControl and MainActivity to keep the code clean.

### Issues
Resolves #77

### CODE REVIEW

**Review by NilsDunlop — APPROVED** [review]
Nicely spotted out. Good job!

**Review by puerto-hub — APPROVED** [review]
Good idea to remove unnecessary code!

**Review by Marble879 — APPROVED** [review]
Good job on finding these redundancies!

**Review by gusasino — COMMENTED** [review]
Great work!

**Pull request merged**
